FROM ghcr.io/yinjiayi/k3s-alpine:3.20-riscv64.1 AS source
ARG SOURCE_COMMIT
RUN apk add --no-cache curl && \
    curl --fail --location --retry 10 --retry-all-errors \
      "https://codeload.github.com/k3s-io/klipper-lb/tar.gz/${SOURCE_COMMIT}" \
      --output /tmp/source.tar.gz && \
    mkdir -p /src && \
    tar -C /src --strip-components=1 -xzf /tmp/source.tar.gz && \
    rm -f /tmp/source.tar.gz

FROM ghcr.io/yinjiayi/k3s-alpine:3.20-riscv64.1
ARG BUILDDATE
LABEL org.opencontainers.image.created=$BUILDDATE
RUN apk add --no-cache iptables ip6tables nftables iptables-legacy
COPY --from=source /src/entry /usr/bin/entry
RUN chmod 0755 /usr/bin/entry
CMD ["entry"]
